// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCsNGtvAbxIE98YgXC53xNqfrJL-_z_YCc',
    appId: '1:342410021995:web:20671c62f0e4373217352e',
    messagingSenderId: '342410021995',
    projectId: 'base-de-datos-ovnicore',
    authDomain: 'base-de-datos-ovnicore.firebaseapp.com',
    storageBucket: 'base-de-datos-ovnicore.firebasestorage.app',
    measurementId: 'G-YY9VB1T4BP',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAdn2LAL-7cDRbcqAUmK11IJ5ovGIkkIGw',
    appId: '1:342410021995:android:c46d347d39278c1e17352e',
    messagingSenderId: '342410021995',
    projectId: 'base-de-datos-ovnicore',
    storageBucket: 'base-de-datos-ovnicore.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC1H-jr5mkkriUjJDDctdbkD8wvL0Tnf3k',
    appId: '1:342410021995:ios:1ff7768844d5d6f317352e',
    messagingSenderId: '342410021995',
    projectId: 'base-de-datos-ovnicore',
    storageBucket: 'base-de-datos-ovnicore.firebasestorage.app',
    iosBundleId: 'com.example.ovnicoreInventario',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyC1H-jr5mkkriUjJDDctdbkD8wvL0Tnf3k',
    appId: '1:342410021995:ios:1ff7768844d5d6f317352e',
    messagingSenderId: '342410021995',
    projectId: 'base-de-datos-ovnicore',
    storageBucket: 'base-de-datos-ovnicore.firebasestorage.app',
    iosBundleId: 'com.example.ovnicoreInventario',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCsNGtvAbxIE98YgXC53xNqfrJL-_z_YCc',
    appId: '1:342410021995:web:a670eb35c9edfba317352e',
    messagingSenderId: '342410021995',
    projectId: 'base-de-datos-ovnicore',
    authDomain: 'base-de-datos-ovnicore.firebaseapp.com',
    storageBucket: 'base-de-datos-ovnicore.firebasestorage.app',
    measurementId: 'G-0KXZ09S6T2',
  );
}
